; =======================================================================================
; Regional Hierarchical Inverse Modelling Environment Example Configuration File
; =======================================================================================
; RHIME example configuration file for CH4. Please check through variable paths and 
; names before running.
; Required inputs are marked as such.
; All other inputs are optional (defaults will be used)
; ======================================================================================= 

[INPUT.MEASUREMENTS]
; Input values for extracting observations
; species (str): Species name (check object store for options) e.g. "ch4"
; sites (list): Site codes as a list (check object store for options) e.g. ["MHD"]
; averaging_period (list): Averaged time periods for measurements as a list (must match length of sites)
; start_date (str): Start of observations to extract (format YYYY-MM-DD)
; end_date (str): End of observations to extract (format YYYY-MM-DD) (non-inclusive)

species = "ch4"                  ; (required)
;sites = ["TAC", "RGL", "HFD", "BSD"]           ; (required)
sites = ["TAC"]           ; (required)
;averaging_period = ["24H", "24H", "24H", "24H"]  ; (required)
averaging_period = ["24H"]  ; (required)
start_date = "2018-01-01"        ; (required - but can be specified on command line instead)
end_date = "2018-06-01"          ; (required - but can be specified on command line instead)

; inlet (list/None): Specific measurements inlet height for the site (list - must match number of sites)
; instrument (list/None): Specific instrument for the site (list - must match number of sites)
; calibration_scale (str): Measurement calibration scale to use
; obs_data_level (list/str): Measurement data quality level 
; filters (None, list, or dictionary of None/lists): Data filtering approach to apply
;   list format (applied to all sites): filters = ["pblh_inlet_diff", "pblh_min"]
;   dictionary format: filters = {"TAC": ["pblh_inlet_diff", "pblh_min"], "RGL": None}

;inlet = ["185m", "90m", "100m", "248m"]
inlet = ["185m"]

;instrument = ["picarro", "picarro", "picarro", "picarro"]
instrument = ["picarro"]
;calibration_scale = None
;obs_data_level = [None, None, None, None]
obs_data_level = [None]
;filters = ["localness"]
;filters = {"TAC": ["pblh_min", "pblh_inlet_diff", "RGL": None}  ; apply different filters for each site
  
[INPUT.STORES]
; OpenGHG object stores for various data. NB. All data may come from the same 
;   object store. This facilitates using multiple object stores.
; bc_store (str): Name of object store with Boundary Conditions data
; obs_store (str): Name of object store with measurements data
; footprint_store (str): Name of object store with footprints data
; emissions_store (str): Name of flux emissions object store

bc_store = "shared_store_zarr"
obs_store = "paris_obs_2025"
footprint_store = "merged_footprints"
emissions_store = "shared_store_zarr"

[INPUT.PRIORS]
; Input values for extracting footprints, emissions and boundary conditions files (also uses values from INPUT.MEASUREMENTS)
; domain (str): Name of inversion spatial domain e.g. "EUROPE"
; met_model (str/None):  e.g., 'UKV' or None if applies to all sites
; fp_model (str): Name of LPDM footprints e.g. "NAME"
; fp_height (list/str): List of footprint inlet heights used in model.
; fp_species (str): Species name associated with footprints in the object store (can be "inert")
; emissions_name (list): Name of emissions sources as used when adding flux files to the object store
; bc_input (list/str): Name of boundary conditions data to use from object store

domain = "EUROPE"           ; (required)
met_model = None
fp_model = "name"
;fp_height = ["185m", "90m", "100m", "248m"]
fp_height = ["185m"]
fp_species = "inert"
emissions_name = ["edgar-annual-total"]
bc_input = "camsv22r2_daily"

[INPUT.BASIS_CASE]
; Input values to extract the basis cases to use within the inversion for boundary conditions and emissions
; basis_algorithm (str): Choice of basis function algorithm to use. One of "quadtree" or "weighted"
; bc_basis_case (str): Boundary conditions basis, defaults to "NESW" (looks for file format {bc_basis_case}_{domain}_*.nc)
; bc_basis_directory (str/None): Directory for bc_basis functions. If None provided, creates new folder in openghg_inversions
;                                expecting to find bc_basis_funciton files there. 
; fp_basis_case (str/None): Emissions bases:
; - if specified, looks for file format {fp_basis_case}_{domain}_*.nc
; - if None, creates basis function using algorithm specified and associated parameters
; nbasis: Number of basis functions to use for algorithm-specified basis function (rounded to %4) in domain
; basis_directory (str/None): Directory containing the basis functions (with domain name as subdirectories)
; country_file (str/None): Directory with filename  containing the indices of country boundaries in domain

basis_algorithm = None 
bc_basis_case = "NESW"
; If fp_basis_case is not defined with Intem outerregions (i.e. fp_basis_case = "outerregions_quadtree_...") then nxout must be
; explicitly defined in the ini file nxout=None. 
fp_basis_case = "outerregions_quadtree_ch4_9"
nbasis = 9
basis_directory = "/group/chem/acrg/LPDM/basis_functions/"
bc_basis_directory = "/group/chem/acrg/LPDM/bc_basis_functions/"
country_file = "/group/chem/acrg/LPDM/countries/country_EUROPE_EEZ_PARIS_gapfilled.nc"

[BRISTAU.PDF]
; Definitions of PDF shape and parameters for inputs
; xprior (dict): Emissions scale factor pdfs for fluxes
; bcprior (dict): Boundary conditions pdf
;
; Each of these prior inputs should be dictionary with the name of probability distribution and shape parameters.
; See https://docs.pymc.io/api/distributions/continuous.html
; Current options for the "pdf" parameter include:

xprior   = {"pdf" : "lognormal", "median" : 1, "stdev" : 1}
; For no bc, set "pdf": None
bcprior  = {"pdf" : "normal", "mu" :  1, "sigma" : 0.05}
rprior  = {"pdf" : "lognormal", "median" :  1, "stdev" : 0.1}
sigma2_rep_prior  = {"pdf" : "inverse gamma", "shape" :  1.1, "scale" : 0.001}
sigma2_qx_prior  = {"pdf" : "inverse gamma", "shape" :  1.1, "scale" : 0.001}
kappa_x_prior = {"pdf" : "beta", "shape" : 1.1, "scale" : 1.1}

[BRISTAU.BC_SPLIT]
; Boundary conditions setup
; bc_freq (str/optional): The period over which the baseline is estimated. e.g.
;  - None - one scaling for the whole inversion period
;  - "monthly" - per calendar monthly
;  - "*D" (e.g. "30D") - per number of days (e.g. 30 days)

bc_freq = "monthly"

[BRISTAU.OPTIONS]
; averaging_error (bool): Add variability in averaging period to the measurement error (Note: currently this
;                         doesn't work correctly)
; use_bc (bool): defaults to True. If False, no boundary conditions will be used in the inversion. This
;                implicitly assumes that contributions from the boundary have been subtracted from the
;                observations.

averaging_error = True
use_bc = True

iterations = 50

[BRISTAU.HYPERPARAMETER_OPTIONS]

; sigma_rep (str / float / optional): Input dictating how mole-fraction observational model error is handled. 
;                                     If float, this will be a fixed additive value throughout the inversion. 
;                                     If None, the inversion will proceed with no representation error.
;                                     If string, currently 'global additive' only option - one value estimated (slice sampler) across all sites at all times. 
; 
; sigma_rep_max (float / optional): Only read if sigma_rep is string. Maximum value of sigma_rep allowed in the slice sampler. This truncates the sigma2_rep_prior with upper bound sigma_rep_max**2.
; 
; sigma_qx (str / float): Input dictating how basis function flux process noise stdev is handled. If xprior is lognormal, sigma_qx is the stdev of the log-sapce Gaussian.
;                                     If string, one of 'global', 'inner outer', or 'inner outer country', must be chosen. 
;                                           'global' will infer a single value across all x. 
;                                           'inner outer' will infer 2 values, one for the inner basis functions, one for the outer bfs.
;                                           'inner outer country' will infer a value for the outer bfs and a value for each country group in the inner domain. Country groups defined with inner_basis_country_groups.
;                                     If float, this will be a fixed additive value throughout the inversion. 
; 
; sigma_qx_max (float / optional): Only read if sigma_qx is string. Maximum value of sigma_qx allowed in the slice sampler. This scales the beta [0,1] sigma_qx_prior with upper bound sigma_qx_max**2 [0, sigma_qx_max**2].
; 
; sigma_qbc (float): Boundary condition flux process noise stdev. If bcprior is lognormal, sigma_qbc is the stdev of the log-sapce Gaussian. Currently only flixed value accepted.
; 
; sigma_qr (float): Relaxation parameter flux process noise stdev. If rprior is lognormal, sigma_qr is the stdev of the log-sapce Gaussian. Currently only flixed value accepted.
; 
; min_group_size (int): Minimum number of basis functions within a group for it to be retained as a distincted country group. Only utilised if sigma_qx='inner outer country'
; 
; kappa_x (str / float / optional): Temporal persistance term dictating the rate at which the bf flux process model forecasts decay to their corresponding relaxation term r.
;                                     If string, one of 'global' or 'inner outer' must be chosen. 
;                                           'global' will infer a single value across all x. 
;                                           'inner outer' will infer 2 values, one for the inner basis functions, one for the outer bfs.
;                                     If float, this will be a fixed value throughout the inversion. kappa_x=1 and x_{t+1} estimated from x_t. kappa_x=0 and x_{t+1} estimated from r_t. 
; 
; kappa_x_minfold (int / optional): Minimum number of e-folds in x expected across duration of inversion. Enforces a stationary solution by preventing complete random walk in x. kappa_x_max = 1 - kappa_x_minfold/nperiod
; 
; kappa_bc (None): Currently only None accepted - bc behaves as random walk. Watch this space...
; 
; kappa_r (float / optional): Temporal persistance term dictating the rate at which the relaxation parameter forecast decays to the rprior median. None enforces random walk behavior. 

nxout = 6

sigma_rep = 'global additive'
sigma_rep_max = 100

sigma_qx = 'inner outer country'
sigma_qx_max = 0.5
sigma_qbc = 0.05
sigma_qr = 0.01
min_group_size = 15

kappa_x = 'inner outer'
kappa_x_minfold = 1
kappa_bc = None
kappa_r = 0.5

[BRISTAU.OUTPUT]
; Details of where to write the output
; outputpath (str): Directory to write output
; outputname (str): Unique identifier for output/run name.

outputpath = "/user/work/ro21302/inversion_methods/BRIS-TAU"  ; (required)
outputname = "BRISTAU_TEST"  ; (required)
